//Handle all error
process.on('uncaughtException', (err) => {
    console.log('Caught exception: ' + err);
});

global.__ = __dirname;
// global la obj toan cuc, chua thông tin tổng thể .
// prcess là đối tượng con của global 
// Khai báo them biến môi trường NODE_ENV=dev vào file ~/.bashrc
// sau đó có thể lấy thông số ra như sau.
console.log(process.env.NODE_ENV);
console.log(global.process.env.NODE_ENV)
/* 
[nodemon] starting `node global_variable.js`
dev
dev
[nodemon] clean exit - waiting for changes before restart

 */

 console.log(global)
 /* 
 ////////////
{ console: [Getter],
  global: [Circular],
  process:
   process {
     title: '/usr/bin/node',
     version: 'v8.11.2',
     moduleLoadList:
      [ 'Binding contextify',
        'Binding natives',
        'Binding config',
        'NativeModule events',
        'Binding async_wrap',
        'Binding icu',
        'NativeModule util',
        'NativeModule internal/errors',
        'NativeModule internal/encoding',
        'NativeModule internal/util',
        'Binding util',
        'Binding constants',
        'NativeModule internal/util/types',
        'Binding buffer',
        'NativeModule buffer',
        'NativeModule internal/buffer',
        'Binding uv',
        'NativeModule internal/process',
        'NativeModule internal/process/warning',
        'NativeModule internal/process/next_tick',
        'NativeModule internal/async_hooks',
        'NativeModule internal/process/promises',
        'NativeModule internal/process/stdio',
        'Binding performance',
        'NativeModule perf_hooks',
        'NativeModule internal/linkedlist',
        'NativeModule internal/trace_events_async_hooks',
        'Binding trace_events',
        'NativeModule async_hooks',
        'NativeModule internal/inspector_async_hook',
        'Binding inspector',
        'NativeModule child_process',
        'Binding spawn_sync',
        'Binding pipe_wrap',
        'NativeModule internal/child_process',
        'NativeModule string_decoder',
        'NativeModule net',
        'NativeModule stream',
        'NativeModule internal/streams/legacy',
        'NativeModule _stream_readable',
        'NativeModule internal/streams/BufferList',
        'NativeModule internal/streams/destroy',
        'NativeModule _stream_writable',
        'NativeModule _stream_duplex',
        'NativeModule _stream_transform',
        'NativeModule _stream_passthrough',
        'NativeModule timers',
        'Binding timer_wrap',
        'NativeModule assert',
        'NativeModule internal/net',
        'Binding cares_wrap',
        'Binding tty_wrap',
        'Binding tcp_wrap',
        'Binding stream_wrap',
        'NativeModule dns',
        'NativeModule dgram',
        'Binding udp_wrap',
        'Binding process_wrap',
        'NativeModule internal/socket_list',
        'NativeModule module',
        'NativeModule internal/module',
        'NativeModule internal/url',
        'NativeModule internal/querystring',
        'NativeModule querystring',
        'Binding url',
        'NativeModule vm',
        'NativeModule fs',
        'NativeModule path',
        'Binding fs',
        'Binding fs_event_wrap',
        'NativeModule internal/fs',
        'NativeModule internal/loader/Loader',
        'NativeModule internal/loader/ModuleWrap',
        'Internal Binding module_wrap',
        'NativeModule internal/loader/ModuleMap',
        'NativeModule internal/loader/ModuleJob',
        'NativeModule internal/safe_globals',
        'NativeModule internal/loader/ModuleRequest',
        'NativeModule url',
        'NativeModule internal/loader/search',
        'NativeModule console',
        'NativeModule tty',
        'NativeModule readline',
        'NativeModule internal/readline',
        'Binding signal_wrap' ],
     versions:
      { http_parser: '2.8.0',
        node: '8.11.2',
        v8: '6.2.414.54',
        uv: '1.19.1',
        zlib: '1.2.11',
        ares: '1.10.1-DEV',
        modules: '57',
        nghttp2: '1.29.0',
        napi: '3',
        openssl: '1.0.2o',
        icu: '60.1',
        unicode: '10.0',
        cldr: '32.0',
        tz: '2017c' },
     arch: 'x64',
     platform: 'linux',
     release:
      { name: 'node',
        lts: 'Carbon',
        sourceUrl: 'https://nodejs.org/download/release/v8.11.2/node-v8.11.2.tar.gz',
        headersUrl: 'https://nodejs.org/download/release/v8.11.2/node-v8.11.2-headers.tar.gz' },
     argv:
      [ '/usr/bin/node',
        '/mycode/NodejsLearn/Nodejs_2018/note/global_variable.js' ],
     execArgv: [],
     env:
      { LC_PAPER: 'en_US.UTF-8',
        XDG_VTNR: '7',
        LC_ADDRESS: 'en_US.UTF-8',
        XDG_SESSION_ID: 'c2',
        TERM_PROGRAM: 'vscode',
        CLUTTER_IM_MODULE: 'xim',
        XDG_GREETER_DATA_DIR: '/var/lib/lightdm-data/minh',
        LC_MONETARY: 'en_US.UTF-8',
        GIO_LAUNCHED_DESKTOP_FILE_PID: '1595',
        SESSION: 'ubuntu',
        ANDROID_HOME: '/home/minh/Sdk',
        GPG_AGENT_INFO: '/home/minh/.gnupg/S.gpg-agent:0:1',
        TERM: 'xterm-256color',
        DESKTOP_STARTUP_ID: 'nautilus-2035-hm-/usr/share/code/code-5_TIME55241550',
        XDG_MENU_PREFIX: 'gnome-',
        SHELL: '/bin/bash',
        DERBY_HOME: '/usr/lib/jvm/java-8-oracle/db',
        QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1',
        TERM_PROGRAM_VERSION: '1.23.1',
        LC_NUMERIC: 'en_US.UTF-8',
        UPSTART_SESSION: 'unix:abstract=/com/ubuntu/upstart-session/1000/1649',
        GNOME_KEYRING_CONTROL: '',
        GTK_MODULES: 'gail:atk-bridge:unity-gtk-module',
        USER: 'minh',
        LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
        QT_ACCESSIBILITY: '1',
        LC_TELEPHONE: 'en_US.UTF-8',
        XDG_SESSION_PATH: '/org/freedesktop/DisplayManager/Session0',
        XDG_SEAT_PATH: '/org/freedesktop/DisplayManager/Seat0',
        SSH_AUTH_SOCK: '/run/user/1000/keyring/ssh',
        SESSION_MANAGER: 'local/hm:@/tmp/.ICE-unix/1848,unix/hm:/tmp/.ICE-unix/1848',
        DEFAULTS_PATH: '/usr/share/gconf/ubuntu.default.path',
        GIO_LAUNCHED_DESKTOP_FILE: '/usr/share/applications/code.desktop',
        XDG_CONFIG_DIRS: '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg',
        PATH: '/home/minh/bin:/home/minh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/minh/Sdk/tools:/home/minh/Sdk/platform-tools:/home/minh/Sdk/tools:/home/minh/Sdk/platform-tools',
        DESKTOP_SESSION: 'ubuntu',
        QT_IM_MODULE: 'ibus',
        QT_QPA_PLATFORMTHEME: 'appmenu-qt5',
        LC_IDENTIFICATION: 'en_US.UTF-8',
        JOB: 'dbus',
        PWD: '/mycode/NodejsLearn/Nodejs_2018/note',
        XDG_SESSION_TYPE: 'x11',
        JAVA_HOME: '/usr/lib/jvm/java-8-oracle',
        XMODIFIERS: '@im=ibus',
        LANG: 'en_US.UTF-8',
        GNOME_KEYRING_PID: '',
        GDM_LANG: 'en_US',
        MANDATORY_PATH: '/usr/share/gconf/ubuntu.mandatory.path',
        LC_MEASUREMENT: 'en_US.UTF-8',
        CHROME_DESKTOP: 'Code.desktop',
        IM_CONFIG_PHASE: '1',
        COMPIZ_CONFIG_PROFILE: 'ubuntu',
        NODE_ENV: 'dev',
        PAPERSIZE: 'letter',
        GDMSESSION: 'ubuntu',
        GTK2_MODULES: 'overlay-scrollbar',
        SESSIONTYPE: 'gnome-session',
        HOME: '/home/minh',
        SHLVL: '2',
        XDG_SEAT: 'seat0',
        LANGUAGE: 'en_US',
        VSCODE_NLS_CONFIG: '{"locale":"en-us","availableLanguages":{}}',
        GNOME_DESKTOP_SESSION_ID: 'this-is-deprecated',
        XDG_SESSION_DESKTOP: 'ubuntu',
        LOGNAME: 'minh',
        VSCODE_NODE_CACHED_DATA_DIR_1595: '/home/minh/.config/Code/CachedData/d0182c3417d225529c6d5ad24b7572815d0de9ac',
        VSCODE_IPC_HOOK: '/run/user/1000/vscode-ca2e2c2c-1.23.1-main.sock',
        XDG_DATA_DIRS: '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop',
        DBUS_SESSION_BUS_ADDRESS: 'unix:abstract=/tmp/dbus-6qYf80wO9M',
        QT4_IM_MODULE: 'xim',
        J2SDKDIR: '/usr/lib/jvm/java-8-oracle',
        LESSOPEN: '| /usr/bin/lesspipe %s',
        VSCODE_PID: '1595',
        INSTANCE: '',
        DISPLAY: ':0',
        XDG_RUNTIME_DIR: '/run/user/1000',
        XDG_CURRENT_DESKTOP: 'Unity',
        GTK_IM_MODULE: 'ibus',
        J2REDIR: '/usr/lib/jvm/java-8-oracle/jre',
        LESSCLOSE: '/usr/bin/lesspipe %s %s',
        LC_TIME: 'en_US.UTF-8',
        LC_NAME: 'en_US.UTF-8',
        XAUTHORITY: '/home/minh/.Xauthority',
        _: '/usr/bin/nodemon' },
     pid: 5808,
     features:
      { debug: false,
        uv: true,
        ipv6: true,
        tls_npn: true,
        tls_alpn: true,
        tls_sni: true,
        tls_ocsp: true,
        tls: true },
     ppid: 5796,
     execPath: '/usr/bin/node',
     debugPort: 9229,
     _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
     _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
     _getActiveRequests: [Function: _getActiveRequests],
     _getActiveHandles: [Function: _getActiveHandles],
     reallyExit: [Function: reallyExit],
     abort: [Function: abort],
     chdir: [Function: chdir],
     cwd: [Function: cwd],
     umask: [Function: umask],
     getuid: [Function: getuid],
     geteuid: [Function: geteuid],
     setuid: [Function: setuid],
     seteuid: [Function: seteuid],
     setgid: [Function: setgid],
     setegid: [Function: setegid],
     getgid: [Function: getgid],
     getegid: [Function: getegid],
     getgroups: [Function: getgroups],
     setgroups: [Function: setgroups],
     initgroups: [Function: initgroups],
     _kill: [Function: _kill],
     _debugProcess: [Function: _debugProcess],
     _debugPause: [Function: _debugPause],
     _debugEnd: [Function: _debugEnd],
     hrtime: [Function: hrtime],
     cpuUsage: [Function: cpuUsage],
     dlopen: [Function: dlopen],
     uptime: [Function: uptime],
     memoryUsage: [Function: memoryUsage],
     binding: [Function: binding],
     _linkedBinding: [Function: _linkedBinding],
     _setupDomainUse: [Function: _setupDomainUse],
     _events:
      { newListener: [Array],
        removeListener: [Array],
        warning: [Function],
        internalMessage: [Function],
        SIGWINCH: [Array],
        uncaughtException: [Function] },
     _rawDebug: [Function],
     _eventsCount: 6,
     domain: null,
     _maxListeners: undefined,
     _fatalException: [Function],
     _exiting: false,
     assert: [Function],
     config: { target_defaults: [Object], variables: [Object] },
     emitWarning: [Function],
     nextTick: [Function: nextTick],
     _tickCallback: [Function: _tickCallback],
     _tickDomainCallback: [Function: _tickDomainCallback],
     stdout: [Getter],
     stderr: [Getter],
     stdin: [Getter],
     openStdin: [Function],
     exit: [Function],
     kill: [Function],
     _immediateCallback: [Function: processImmediate],
     channel:
      Pipe {
        writeQueueSize: 0,
        buffering: false,
        onread: [Function],
        sockets: [Object] },
     _channel: [Getter/Setter],
     _handleQueue: null,
     _pendingMessage: null,
     send: [Function],
     _send: [Function],
     connected: true,
     disconnect: [Function],
     _disconnect: [Function],
     argv0: '/usr/bin/node',
     mainModule:
      Module {
        id: '.',
        exports: {},
        parent: null,
        filename: '/mycode/NodejsLearn/Nodejs_2018/note/global_variable.js',
        loaded: false,
        children: [],
        paths: [Array] } },
  Buffer:
   { [Function: Buffer]
     poolSize: 8192,
     from: [Function],
     alloc: [Function],
     allocUnsafe: [Function],
     allocUnsafeSlow: [Function],
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function],
     concat: [Function],
     byteLength: [Function: byteLength],
     [Symbol(node.isEncoding)]: [Function] },
  clearImmediate: [Function],
  clearInterval: [Function],
  clearTimeout: [Function],
  setImmediate: { [Function: setImmediate] [Symbol(util.promisify.custom)]: [Function] },
  setInterval: [Function],
  setTimeout: { [Function: setTimeout] [Symbol(util.promisify.custom)]: [Function] },
  __: '/mycode/NodejsLearn/Nodejs_2018/note' }
////////////
 */
